databases:
  - name: blogdb
    plan: free
    databaseName: blog
    user: blog

services:
  - type: web
    plan: free
    name: blog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ll_project.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blogdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4